controller_manager:
  ros__parameters:
    update_rate: 10

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:
    publish_rate: 10.0
    base_frame_id: base_link
    odom_frame_id: odom
    enable_odom_tf: false   # robot_localization EKF publishes odom->base_link (config/ekf.yaml)
    pose_covariance_diagonal:  [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheel_separation: 0.1895
    wheel_radius: 0.06985
    use_stamped_vel: false

joint_broad:
  ros__parameters:
    usage: "publishing joint states"
